from . import Module, Setting

class Minio(Module):
    enable: Setting = Setting(
        name="services.minio.enable",
        type="bool",
        default=False,
        description="Whether to enable Minio Object Storage.",
        example="true",
    )

    secretKey: Setting = Setting(
        name="services.minio.secretKey",
        type="string",
        default="",
        description="Specify the Secret key of 8 to 40 characters in length that clients use to access the server. This overrides the secret key that is generated by minio on first startup and stored inside the configDir directory.",
    )

    rootCredentialsFile: Setting = Setting(
        name="services.minio.rootCredentialsFile",
        type={"nullOr": "path"},
        default="null",
        description="File containing the MINIO_ROOT_USER, default is “minioadmin”, and MINIO_ROOT_PASSWORD (length >= 8), default is “minioadmin”; in the format of an EnvironmentFile=, as described by systemd.exec(5)."
    )

    region: Setting = Setting(
        name="services.minio.region",
        type="string",
        default="us-east-1",
        description="The physical location of the server. By default it is set to us-east-1, which is same as AWS S3’s and Minio’s default region.",
    )

    package: Setting = Setting(
        name="services.minio.package",
        type="package",
        default="pkgs.minio",
        description="Minio package to use.",
    )

    listenAddress: Setting = Setting(
        name="services.minio.listenAddress",
        type="string",
        default=":9000",
        description="IP address and port of the server.",
    )

    dataDir: Setting = Setting(
        name="services.minio.dataDir",
        type={"listOf": "string"},
        default=["/var/lib/minio/data"],
        description="The list of data directories for storing the objects. Use one path for regular operation and the minimum of 4 endpoints for Erasure Code mode.",
    )

    consoleAddress: Setting = Setting(
        name="services.minio.consoleAddress",
        type="string",
        default=":9001",
        description="IP address and port of the web UI (console).",
    )

    configDir: Setting = Setting(
        name="services.minio.configDir",
        type="path",
        default="/var/lib/minio/config",
        description="The config directory, for the access keys and other settings.",
    )

    browser: Setting = Setting(
        name="services.minio.browser",
        type="bool",
        default="true",
        description="Enable or disable access to web UI.",
    )

    accessKey: Setting = Setting(
        name="services.minio.accessKey",
        type="string",
        default="",
        description="Access key of 5 to 20 characters in length that clients use to access the server. This overrides the access key that is generated by minio on first startup and stored inside the configDir directory.",
    )
