name: "Run command with Nix cache upload"
inputs:
  # The script to run
  script:
    description: "The script to run"
    required: true
  working-directory:
    description: "The working directory to run the script in"
    required: false
    default: "."
  attic_token:
    description: "The token to use for authenticating with the Attic cache."
    required: false
    default: ""
runs:
  using: "composite"
  # env:
  #   ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
  steps:
    - if: ${{ inputs.ATTIC_TOKEN != '' }}
      name: Run script
      shell: bash
      run: |
        ATTIC_PUSH_PID=
        attic watch-store "thymis-cache:public-cache" &
        ATTIC_PID=$!
        trap 'kill $ATTIC_PID; if [ -n "$ATTIC_PUSH_PID" ]; then kill $ATTIC_PUSH_PID; fi; true' EXIT
        ${{ inputs.script }}
        EXIT_CODE=$?
        if [ -e result ]; then
          attic push thymis-cache:public-cache result &
          ATTIC_PUSH_PID=$!
          sleep 5
        fi
        exit $EXIT_CODE
      working-directory: ${{ inputs.working-directory }}
    - if: ${{ inputs.ATTIC_TOKEN == '' }}
      name: Run script
      shell: bash
      run: ${{ inputs.script }}
      working-directory: ${{ inputs.working-directory }}
