"""add-secrets-column-include-in-image-and-processing

Revision ID: 06d5e3945df0
Revises: 0e4e49216386
Create Date: 2025-03-03 20:41:28.975075

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06d5e3945df0"
down_revision = "0e4e49216386"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # clear the old table due to the new column not being nullable, and previous only being dev
    op.execute("DELETE FROM secrets")
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("include_in_image", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "processing_type",
                sa.Enum("NONE", "MKPASSWD_YESCRYPT", name="secretprocessingtypes"),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )
        batch_op.drop_column("processing_type")
        batch_op.drop_column("include_in_image")

    # ### end Alembic commands ###
