"""add-secrets

Revision ID: 0e4e49216386
Revises: a8d5ad9db0f0
Create Date: 2025-03-02 20:19:57.525490

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e4e49216386"
down_revision = "a8d5ad9db0f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "SINGLE_LINE", "MULTI_LINE", "ENV_LIST", "FILE", name="secrettypes"
            ),
            nullable=False,
        ),
        sa.Column("value_enc", sa.LargeBinary(), nullable=False),
        sa.Column("value_size", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delete_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secrets")
    # ### end Alembic commands ###
