"""add-last-seen-to-deployment-info-and-devices

Revision ID: 11b36810c433
Revises: f1997e82baa2
Create Date: 2025-02-21 16:36:24.951384

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "11b36810c433"
down_revision = "f1997e82baa2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployment_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("first_seen", sa.DateTime(), nullable=True))

    with op.batch_alter_table("hardware_devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hardware_devices", schema=None) as batch_op:
        batch_op.drop_column("last_seen")

    with op.batch_alter_table("deployment_info", schema=None) as batch_op:
        batch_op.drop_column("first_seen")
        batch_op.drop_column("last_seen")

    # ### end Alembic commands ###
