"""add-log-table

Revision ID: 142c94c6b394
Revises: 06d5e3945df0
Create Date: 2025-04-29 14:17:13.901279

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "142c94c6b394"
down_revision = "06d5e3945df0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Uuid(), nullable=False, primary_key=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("hostname", sa.String(), nullable=False),
        sa.Column("facility", sa.Integer(), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("programname", sa.String(), nullable=False),
        sa.Column("syslogtag", sa.String(), nullable=False),
        sa.Column("deployment_info_id", sa.Uuid(), nullable=True),
        sa.Column("ssh_public_key", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_info_id"],
            ["deployment_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("log_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_log_entries_id"), ["id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_log_entries_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("log_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_log_entries_id"))

    op.drop_table("log_entries")
    # ### end Alembic commands ###
