"""added host keys and images

Revision ID: 02cb9f4abdab
Revises: e2fc6c08d9f6
Create Date: 2024-09-10 17:33:11.005199

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02cb9f4abdab"
down_revision = "e2fc6c08d9f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hostkeys",
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("build_hash", sa.String(), nullable=True),
        sa.Column("public_key", sa.String(), nullable=True),
        sa.Column("device_host", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(
        op.f("ix_hostkeys_identifier"), "hostkeys", ["identifier"], unique=False
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifier", sa.String(), nullable=True),
        sa.Column("build_hash", sa.String(), nullable=True),
        sa.Column("commit_hash", sa.String(), nullable=True),
        sa.Column("device_state", sa.JSON(), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("ix_hostkeys_identifier"), table_name="hostkeys")
    op.drop_table("hostkeys")
    # ### end Alembic commands ###
