"""add-access-client-token

Revision ID: bc8f00254345
Revises: 179b9ee7a67d
Create Date: 2025-01-31 18:15:21.626350

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc8f00254345"
down_revision = "179b9ee7a67d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_client_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("for_deployment_info_id", sa.Uuid(), nullable=False),
        sa.Column("deploy_device_task_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deploy_device_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["for_deployment_info_id"],
            ["deployment_info.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        op.f("ix_access_client_tokens_deploy_device_task_id"),
        "access_client_tokens",
        ["deploy_device_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_client_tokens_for_deployment_info_id"),
        "access_client_tokens",
        ["for_deployment_info_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_client_tokens_token"),
        "access_client_tokens",
        ["token"],
        unique=True,
    )

    # op.alter_column('agent_tokens', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    with op.batch_alter_table("agent_tokens") as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "agent_tokens", "created_at", existing_type=sa.DATETIME(), nullable=True
    # )
    with op.batch_alter_table("agent_tokens") as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
    op.drop_index(
        op.f("ix_access_client_tokens_token"), table_name="access_client_tokens"
    )
    op.drop_index(
        op.f("ix_access_client_tokens_for_deployment_info_id"),
        table_name="access_client_tokens",
    )
    op.drop_index(
        op.f("ix_access_client_tokens_deploy_device_task_id"),
        table_name="access_client_tokens",
    )
    op.drop_table("access_client_tokens")
    # ### end Alembic commands ###
