"""add-user-session-id-column-to-task

Revision ID: a8d5ad9db0f0
Revises: cf011834f9aa
Create Date: 2025-02-11 16:39:46.689359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8d5ad9db0f0"
down_revision = "cf011834f9aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_session_id", sa.Uuid(), nullable=True))
        # batch_op.create_foreign_key(None, "sessions", ["user_session_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_tasks_user_session_id_sessions", "sessions", ["user_session_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(
            "fk_tasks_user_session_id_sessions", type_="foreignkey"
        )
        batch_op.drop_column("user_session_id")

    # ### end Alembic commands ###
