"""add agent tokens

Revision ID: 9dc5fb3bec50
Revises: b41f88f5679a
Create Date: 2025-01-22 22:16:43.145820

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9dc5fb3bec50"
down_revision = "b41f88f5679a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_disk_config_commit", sa.String(), nullable=False),
        sa.Column("original_disk_config_id", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_tokens_id"), "agent_tokens", ["id"], unique=False)
    op.create_index(
        op.f("ix_agent_tokens_token"), "agent_tokens", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_tokens_token"), table_name="agent_tokens")
    op.drop_index(op.f("ix_agent_tokens_id"), table_name="agent_tokens")
    op.drop_table("agent_tokens")
    # ### end Alembic commands ###
