"""empty message

Revision ID: 40befde2965c
Revises: e059c84cf3fc
Create Date: 2026-03-09 17:47:08.617158

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "40befde2965c"
down_revision = "e059c84cf3fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_processes",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("process_index", sa.Integer(), nullable=False),
        sa.Column("process_program", sa.String(length=255), nullable=True),
        sa.Column("process_args", sa.JSON(), nullable=True),
        sa.Column("process_env", sa.JSON(), nullable=True),
        sa.Column("process_stdout", sa.LargeBinary(), nullable=True),
        sa.Column("process_stderr", sa.LargeBinary(), nullable=True),
        sa.Column("nix_status", sa.JSON(), nullable=True),
        sa.Column("nix_errors", sa.JSON(), nullable=True),
        sa.Column("nix_files_linked", sa.Integer(), nullable=True),
        sa.Column("nix_bytes_linked", sa.BigInteger(), nullable=True),
        sa.Column("nix_corrupted_paths", sa.Integer(), nullable=True),
        sa.Column("nix_untrusted_paths", sa.Integer(), nullable=True),
        sa.Column("nix_error_logs", sa.JSON(), nullable=True),
        sa.Column("nix_warning_logs", sa.JSON(), nullable=True),
        sa.Column("nix_notice_logs", sa.JSON(), nullable=True),
        sa.Column("nix_info_logs", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "process_index"),
    )

    # migrate existing process data from tasks table to task_processes table
    op.execute(
        "INSERT INTO task_processes (task_id, process_index, process_program, process_args, process_env, process_stdout, process_stderr, nix_status, nix_errors, nix_files_linked, nix_bytes_linked, nix_corrupted_paths, nix_untrusted_paths, nix_error_logs, nix_warning_logs, nix_notice_logs, nix_info_logs) SELECT id, 0, process_program, process_args, process_env, process_stdout, process_stderr, nix_status, nix_errors, nix_files_linked, nix_bytes_linked, nix_corrupted_paths, nix_untrusted_paths, nix_error_logs, nix_warning_logs, nix_notice_logs, nix_info_logs FROM tasks"
    )

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("nix_error_logs")
        batch_op.drop_column("process_env")
        batch_op.drop_column("process_stdout")
        batch_op.drop_column("nix_notice_logs")
        batch_op.drop_column("process_args")
        batch_op.drop_column("nix_status")
        batch_op.drop_column("process_program")
        batch_op.drop_column("nix_untrusted_paths")
        batch_op.drop_column("nix_warning_logs")
        batch_op.drop_column("nix_files_linked")
        batch_op.drop_column("nix_info_logs")
        batch_op.drop_column("nix_corrupted_paths")
        batch_op.drop_column("process_stderr")
        batch_op.drop_column("nix_bytes_linked")
        batch_op.drop_column("nix_errors")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nix_errors", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("nix_bytes_linked", sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column("process_stderr", sa.BLOB(), nullable=True))
        batch_op.add_column(
            sa.Column("nix_corrupted_paths", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("nix_info_logs", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("nix_files_linked", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("nix_warning_logs", sqlite.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("nix_untrusted_paths", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("process_program", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("nix_status", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("process_args", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("nix_notice_logs", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("process_stdout", sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column("process_env", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("nix_error_logs", sqlite.JSON(), nullable=True))

    # migrate process data back from task_processes table to tasks table, only for process_index = 0 (the first process)
    op.execute(
        "UPDATE tasks SET process_program = (SELECT process_program FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), process_args = (SELECT process_args FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), process_env = (SELECT process_env FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), process_stdout = (SELECT process_stdout FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), process_stderr = (SELECT process_stderr FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_status = (SELECT nix_status FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_errors = (SELECT nix_errors FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_files_linked = (SELECT nix_files_linked FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_bytes_linked = (SELECT nix_bytes_linked FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_corrupted_paths = (SELECT nix_corrupted_paths FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_untrusted_paths = (SELECT nix_untrusted_paths FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_error_logs = (SELECT nix_error_logs FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_warning_logs = (SELECT nix_warning_logs FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_notice_logs = (SELECT nix_notice_logs FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0), nix_info_logs = (SELECT nix_info_logs FROM task_processes WHERE task_processes.task_id = tasks.id AND process_index = 0)"
    )

    op.drop_table("task_processes")
    # ### end Alembic commands ###
