"""added model for tasks

Revision ID: 44aeb6abdcab
Revises: 02cb9f4abdab
Create Date: 2024-11-21 14:47:51.595656

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "44aeb6abdcab"
down_revision = "02cb9f4abdab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
