"""add_network_interfaces_location_to_deployment_info

Revision ID: 6a32d509779a
Revises: a1b2c3d4e5f6
Create Date: 2026-04-01 12:50:53.734067

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6a32d509779a"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deployment_info_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("ram_percent", sa.Float(), nullable=False),
        sa.Column("disk_percent", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_info_id"],
            ["deployment_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("device_metrics", schema=None) as batch_op:
        batch_op.create_index(
            "ix_device_metrics_deployment_timestamp",
            ["deployment_info_id", "timestamp"],
            unique=False,
        )

    with op.batch_alter_table("controller_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "auto_update_schedule",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=512),
            existing_nullable=False,
            existing_server_default=sa.text("'daily'"),
        )

    with op.batch_alter_table("deployment_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("network_interfaces", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("location", sa.Text(), nullable=True))

    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("deployment_info", schema=None) as batch_op:
        batch_op.drop_column("location")
        batch_op.drop_column("network_interfaces")

    with op.batch_alter_table("controller_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "auto_update_schedule",
            existing_type=sa.String(length=512),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
            existing_server_default=sa.text("'daily'"),
        )

    with op.batch_alter_table("device_metrics", schema=None) as batch_op:
        batch_op.drop_index("ix_device_metrics_deployment_timestamp")

    op.drop_table("device_metrics")
    # ### end Alembic commands ###
