"""allow-hardware-device-without-deployment-info

Revision ID: 9839fa566965
Revises: 11b36810c433
Create Date: 2025-02-21 22:14:36.085991

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9839fa566965"
down_revision = "11b36810c433"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hardware_devices", schema=None) as batch_op:
        batch_op.alter_column(
            "deployment_info_id", existing_type=sa.CHAR(length=32), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hardware_devices", schema=None) as batch_op:
        batch_op.alter_column(
            "deployment_info_id", existing_type=sa.CHAR(length=32), nullable=False
        )

    # ### end Alembic commands ###
