"""added deployment_info and hardware_device

Revision ID: b41f88f5679a
Revises: 44aeb6abdcab
Create Date: 2024-12-18 02:05:04.287386

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "b41f88f5679a"
down_revision = "44aeb6abdcab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployment_info",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ssh_public_key", sa.String(), nullable=False),
        sa.Column("deployed_config_commit", sa.String(), nullable=False),
        sa.Column("deployed_config_id", sa.String(), nullable=False),
        sa.Column("reachable_deployed_host", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ssh_public_key"),
    )
    op.create_index(
        op.f("ix_deployment_info_id"), "deployment_info", ["id"], unique=False
    )
    op.create_table(
        "hardware_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hardware_id", sa.String(), nullable=False),
        sa.Column("deployment_info_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_info_id"],
            ["deployment_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hardware_devices_id"), "hardware_devices", ["id"], unique=False
    )
    op.drop_index("ix_images_id", table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("identifier", sa.VARCHAR(), nullable=True),
        sa.Column("build_hash", sa.VARCHAR(), nullable=True),
        sa.Column("commit_hash", sa.VARCHAR(), nullable=True),
        sa.Column("device_state", sqlite.JSON(), nullable=True),
        sa.Column("valid", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_images_id", "images", ["id"], unique=False)
    op.drop_index(op.f("ix_hardware_devices_id"), table_name="hardware_devices")
    op.drop_table("hardware_devices")
    op.drop_index(op.f("ix_deployment_info_id"), table_name="deployment_info")
    op.drop_table("deployment_info")
    # ### end Alembic commands ###
