"""make-task-id-nullable

Revision ID: e059c84cf3fc
Revises: 9c84d1271466
Create Date: 2025-06-20 16:12:05.989844

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e059c84cf3fc"
down_revision = "9c84d1271466"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("access_client_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "deploy_device_task_id", existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table("log_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_log_entries_id"))
        batch_op.create_index(batch_op.f("ix_log_entries_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("log_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_log_entries_id"))
        batch_op.create_index(batch_op.f("ix_log_entries_id"), ["id"], unique=1)

    with op.batch_alter_table("access_client_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "deploy_device_task_id", existing_type=sa.CHAR(length=32), nullable=False
        )
    # ### end Alembic commands ###
