"""added hostkeys

Revision ID: e95629b78fad
Revises: e2fc6c08d9f6
Create Date: 2024-08-26 22:34:15.094782

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e95629b78fad"
down_revision = "e2fc6c08d9f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hostkeys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_hash", sa.String(), nullable=True),
        sa.Column("public_key", sa.String(), nullable=True),
        sa.Column("identifier", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("build_hash"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_index(op.f("ix_hostkeys_id"), "hostkeys", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hostkeys_id"), table_name="hostkeys")
    op.drop_table("hostkeys")
    # ### end Alembic commands ###
