"""empty message

Revision ID: f1997e82baa2
Revises: bc8f00254345
Create Date: 2025-02-11 14:09:08.357840

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1997e82baa2"
down_revision = "bc8f00254345"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DELETE FROM hardware_devices WHERE hardware_ids IS '{}'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
