name: "Build Devices"
on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  build-thymis-controller-pi-3-sd-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbhi/qus/action@main
        with:
          targets: aarch64
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            system-features = kvm
            extra-trusted-public-keys = cache.thymis.io-1:pEeKkNXiK17TLKls0KM8cEp0NGy08gc5chAmCyuQo8M=
            extra-substituters = https://cache.thymis.io
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: pin nixpkgs
        run: nix registry add nixpkgs github:NixOS/nixpkgs/nixos-24.05
      - name: build thymis-controller-pi-3-sd-image
        run: nix build .#thymis-controller-pi-3-sd-image --print-build-logs

  build-thymis-controller-pi-4-sd-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbhi/qus/action@main
        with:
          targets: aarch64
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            system-features = kvm
            extra-trusted-public-keys = cache.thymis.io-1:pEeKkNXiK17TLKls0KM8cEp0NGy08gc5chAmCyuQo8M=
            extra-substituters = https://cache.thymis.io
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: pin nixpkgs
        run: nix registry add nixpkgs github:NixOS/nixpkgs/nixos-24.05
      - name: build thymis-controller-pi-4-sd-image
        run: nix build .#thymis-controller-pi-4-sd-image --print-build-logs

  build-thymis-controller-pi-5-sd-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbhi/qus/action@main
        with:
          targets: aarch64
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            system-features = kvm
            extra-trusted-public-keys = cache.thymis.io-1:pEeKkNXiK17TLKls0KM8cEp0NGy08gc5chAmCyuQo8M=
            extra-substituters = https://cache.thymis.io
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: pin nixpkgs
        run: nix registry add nixpkgs github:NixOS/nixpkgs/nixos-24.05
      - name: build thymis-controller-pi-5-sd-image
        run: nix build .#thymis-controller-pi-5-sd-image --print-build-logs
