name: "Build Devices"
on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  build-thymis-controller-pi-3-sd-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            system-features = kvm
            extra-trusted-public-keys = cache.thymis.io-1:pEeKkNXiK17TLKls0KM8cEp0NGy08gc5chAmCyuQo8M=
            extra-substituters = https://cache.thymis.io
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: build thymis-controller-pi-3-sd-image
        run: nix build .#thymis-controller-pi-3-sd-image --print-build-logs
      - name: assemble image with a empty secrets dir
        run: |
          mkdir -p workdir/secrets
          echo "abcdefgh" > workdir/secrets/whatever.txt
          ./result workdir/secrets workdir/final
      - name: assert something exists at workdir/final*
        run: |
          if test -n "$(find ./workdir -maxdepth 1 -name 'final*' -print -quit)"
          then
            echo "found something at workdir/final*"
          else
            echo "nothing found at workdir/final*"
            exit 1
          fi

  build-thymis-controller-pi-4-sd-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            system-features = kvm
            extra-trusted-public-keys = cache.thymis.io-1:pEeKkNXiK17TLKls0KM8cEp0NGy08gc5chAmCyuQo8M=
            extra-substituters = https://cache.thymis.io
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: build thymis-controller-pi-4-sd-image
        run: nix build .#thymis-controller-pi-4-sd-image --print-build-logs
      - name: assemble image with a empty secrets dir
        run: |
          mkdir -p workdir/secrets
          echo "abcdefgh" > workdir/secrets/whatever.txt
          ./result workdir/secrets workdir/final
      - name: assert something exists at workdir/final*
        run: |
          if test -n "$(find ./workdir -maxdepth 1 -name 'final*' -print -quit)"
          then
            echo "found something at workdir/final*"
          else
            echo "nothing found at workdir/final*"
            exit 1
          fi

  build-thymis-controller-pi-5-sd-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            system-features = kvm
            extra-trusted-public-keys = cache.thymis.io-1:pEeKkNXiK17TLKls0KM8cEp0NGy08gc5chAmCyuQo8M=
            extra-substituters = https://cache.thymis.io
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: build thymis-controller-pi-5-sd-image
        run: nix build .#thymis-controller-pi-5-sd-image --print-build-logs
      - name: assemble image with a empty secrets dir
        run: |
          mkdir -p workdir/secrets
          echo "abcdefgh" > workdir/secrets/whatever.txt
          ./result workdir/secrets workdir/final
      - name: assert something exists at workdir/final*
        run: |
          if test -n "$(find ./workdir -maxdepth 1 -name 'final*' -print -quit)"
          then
            echo "found something at workdir/final*"
          else
            echo "nothing found at workdir/final*"
            exit 1
          fi
